## Question - 1
ans - 

In [1]:
from sklearn.datasets import load_iris

df = load_iris()

In [2]:
import pandas as pd
import numpy as np

In [3]:
x = pd.DataFrame(df.data , columns= df.feature_names , )

In [4]:
y = df.target

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier()

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.30 , random_state=42)


classifier.fit(x_train , y_train)

KNeighborsClassifier()

In [7]:
y_pred = classifier.predict(x_test)

In [8]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report


print(confusion_matrix (y_test , y_pred))
print(classification_report(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

1.0


## Question - 2
ans - 

In [9]:
from sklearn.datasets import fetch_california_housing

df1= fetch_california_housing()

x1 = pd.DataFrame(df1.data , columns = df1.feature_names)

y1 = df1.target


x1_train , x1_test , y1_train , y1_test = train_test_split(x1, y1 , test_size=0.30 , random_state=0)

from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor()

regressor.fit(x1_train , y1_train)


KNeighborsRegressor()

In [10]:
y_pred1 = regressor.predict(x1_test)

In [11]:
from sklearn.metrics import r2_score  , mean_squared_error

print(f"r2 score is {r2_score(y_pred1  , y1_test)}")

print(mean_squared_error(y_pred1  , y1_test))

r2 score is -2.530705697564586
1.1464552020677925


## Question - 3
ans - 

In [14]:
from sklearn.model_selection import GridSearchCV

parameters= {'n_neighbors':[5,6,7,8,9,10]}

grid_classifier = GridSearchCV(KNeighborsClassifier() , param_grid= parameters)

In [15]:
grid_classifier.fit(x_train , y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [5, 6, 7, 8, 9, 10]})

In [16]:
grid_classifier.best_params_

{'n_neighbors': 7}

## Question - 4
ans - 

In [18]:
from sklearn.datasets import fetch_california_housing

california = fetch_california_housing()




In [20]:
x2 = pd.DataFrame(california.data , columns = california.feature_names)

y2 = california.target

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x2_train , x2_test , y2_train , y2_test = train_test_split(x2 , y2 , test_size= 0.30 , random_state=0)

In [24]:
x2_train_scaled = scaler.fit_transform(x2_train)

x2_test_scaled = scaler.transform(x2_test)

In [26]:
regressor.fit(x2_train_scaled , y2_train)

KNeighborsRegressor()

In [27]:
y_pred2 = regressor.predict(x2_test_scaled)

In [28]:
from sklearn.metrics import r2_score  , mean_squared_error

print(f"r2 score is {r2_score(y_pred2  , y2_test)}")

print(mean_squared_error(y_pred2  , y2_test))

r2 score is 0.5585707159435935
0.43041225004770467


## Question - 5
ans - 

In [31]:
from sklearn.datasets import load_iris

iris = load_iris()

x3 = pd.DataFrame(iris.data , columns = iris.feature_names)

y3 = iris.target

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x3_train ,x3_test , y3_train , y3_test = train_test_split(x3 , y3 , test_size=0.25 , random_state=0)

In [33]:
x3_train_scaled = scaler.fit_transform(x3_train)
x3_test_scaled = scaler.transform(x3_test)

In [35]:
knn_classifier = KNeighborsClassifier(weights='distance')

knn_classifier.fit(x3_train_scaled , y3_train)

KNeighborsClassifier(weights='distance')

In [36]:
y_pred3 = knn_classifier.predict(x3_test_scaled)

In [37]:
print(accuracy_score(y_pred3 , y3_test))

0.9736842105263158


## Question - 6
ans - 

In [38]:
def standardising(x_train , x_test):
    
    
    scaler = StandardScaler()
    
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)
    
    
    return x_train_scaled , x_test_scaled

In [39]:
standardising(x1_train , x1_test)

(array([[-1.00030408,  1.8562098 , -1.146823  , ...,  0.25982829,
          0.51396387, -0.11131397],
        [-0.84938602,  1.14171192, -0.76585476, ..., -0.00327132,
          0.99993462, -1.3173838 ],
        [ 1.28620508, -0.92239307,  0.46102722, ...,  0.11210392,
         -0.82245571,  0.76084397],
        ...,
        [-0.35374656,  0.18904808, -0.77908241, ..., -0.1818844 ,
          0.44387193, -1.16288725],
        [ 0.93323448,  0.42721404, -0.38591908, ..., -0.1154139 ,
         -0.9392756 ,  0.81566532],
        [-1.31060093, -1.08117038, -0.65304797, ...,  0.05761909,
         -1.32244485,  1.99681635]]),
 array([[ 0.15077666, -0.5254498 ,  0.10477153, ...,  0.16599986,
         -1.42524636,  1.25423617],
        [ 1.01154901,  0.26843673,  0.29893351, ..., -0.00284492,
         -0.79909173,  0.79573028],
        [ 0.25489638,  0.03027077,  0.22177006, ..., -0.01898759,
          1.41114065, -1.13298469],
        ...,
        [ 2.11958585,  0.10965942,  0.93004803, ..., -

## Question - 7
ans - 

In [40]:
def eucledian(x1,x2,y1,y2):
    
    distance = (x2-x1)**2 + (y2-y1)**2
    
    return distance

In [41]:
eucledian(5,8,3,9)

45

## Question - 8
ans - 

In [43]:
def manhatten(x1,x2,y1,y2):
    
    manhatten_distance = abs(x2-x1) + abs(y2-y1)
    
    return manhatten_distance

In [44]:
manhatten(5,8,3,9)

9